# firefox do not read this file, just backing up because I will for sure forget
user_pref("font.default.x-western", "sans-serif");
user_pref("font.name.monospace.x-western", "Courier New");
user_pref("font.name.sans-serif.x-western", "Segoe UI");
user_pref("font.name.serif.x-western", "Arial");
