general {
    lock_cmd = pidof hyprlock || hyprlock
    on_unlock_cmd = ~/.config/hypr/cmd/welcome-back.sh
}

listener {
    timeout = 300 # 5 min
    on-timeout = systemctl --user set-environment LOCK_TS=$(date -Iseconds) && loginctl lock-session
}

listener {
    timeout = 1800 # 30 min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 3600 # 1 hour
    on-timeout = systemctl suspend
}
