source = ./themes/latte.conf
source = ./env.conf
source = ./monitor.conf
source = ./programs.conf
source = ./autostart.conf
source = ./animation.conf
source = ./decoration.conf
source = ./dwindle.conf
source = ./autostart.conf
source = ./bind.conf
source = ./cursor.conf
source = ./device.conf
source = ./general.conf
source = ./input.conf
source = ./master.conf

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
