$terminal = kitty
$fileManager = dolphin
$browser = firefox
$spotify = spotify-launcher
$menu = GTK_THEME=catppuccin_latte wofi --conf ~/.config/wofi/config --style ~/.config/wofi/styles/latte.css
$mainMod = SUPER

